[2025-10-18T18:40:55.378+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: wiki_trending_pipeline.fetch_top_pages manual__2025-10-18T18:40:52.722926+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
